<?php

namespace Database\Seeders;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('menus')->insert([
            [
                'id' => 1,
                'title' => 'Home',
                'icon' => 'pie-chart',
                'url' => 'home',
                'route' => null,
                'parent_id' => null,
                'display_order' => 0,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'title' => 'User Management',
                'icon' => 'users',
                'url' => null,
                'route' => null,
                'parent_id' => 1,
                'display_order' => 1,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'title' => 'Users List',
                'icon' => null,
                'url' => null,
                'route' => 'users.index',
                'parent_id' => 2,
                'display_order' => 2,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'title' => 'Add User',
                'icon' => null,
                'url' => null,
                'route' => 'users.create',
                'parent_id' => 2,
                'display_order' => 3,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'title' => 'User Logs',
                'icon' => null,
                'url' => null,
                'route' => 'user.user-activities',
                'parent_id' => 2,
                'display_order' => 4,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'title' => 'Menu Management',
                'icon' => 'layout',
                'url' => null,
                'route' => 'menus.index',
                'parent_id' => null,
                'display_order' => 5,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'title' => 'Roles Management',
                'icon' => 'tool',
                'url' => null,
                'route' => 'roles.index',
                'parent_id' => null,
                'display_order' => 6,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'title' => 'Client Management',
                'icon' => 'server',
                'url' => null,
                'route' => null,
                'parent_id' => 7,
                'display_order' => 7,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'title' => 'Factories',
                'icon' => 'grid',
                'url' => null,
                'route' => 'factories.index',
                'parent_id' => 8,
                'display_order' => 0,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'title' => 'Sections',
                'icon' => 'map',
                'url' => null,
                'route' => 'sections.index',
                'parent_id' => 8,
                'display_order' => 1,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'title' => 'Section Handlers',
                'icon' => 'users',
                'url' => null,
                'route' => 'handlers.index',
                'parent_id' => 8,
                'display_order' => 3,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'title' => 'Employees',
                'icon' => null,
                'url' => null,
                'route' => 'employees.index',
                'parent_id' => 8,
                'display_order' => 4,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'title' => 'Complaints',
                'icon' => null,
                'url' => null,
                'route' => 'complaints.index',
                'parent_id' => 8,
                'display_order' => 5,
                'level' => 'admin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}